# Generated by Django 2.1.7 on 2019-08-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_details',
            fields=[
                ('ifsc', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('bank_id', models.CharField(max_length=3)),
                ('branch', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'bank',
                'managed': True,
            },
        ),
    ]
