# Generated by Django 2.1.7 on 2019-08-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank_details',
            options={},
        ),
    ]
