# Generated by Django 2.1.7 on 2019-08-20 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_details', '0002_auto_20190820_1503'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bank_details',
            new_name='BankDetails',
        ),
        migrations.AlterModelTable(
            name='bankdetails',
            table=None,
        ),
    ]
