# Generated by Django 2.1.7 on 2019-08-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_details', '0003_auto_20190820_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_id',
            field=models.CharField(max_length=20),
        ),
    ]
