# Generated by Django 2.1.7 on 2019-08-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_details', '0005_auto_20190823_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='branch',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
